export const SHOW_NOTIFICATION_SUCCESS = "SHOW_NOTIFICATION_SUCCESS";
export const SHOW_NOTIFICATION_ERROR = "SHOW_NOTIFICATION_ERROR";
export const SHOW_NOTIFICATION_RESET = "SHOW_NOTIFICATION_RESET";
export const REDIRECT_PAGE = "REDIRECT_PAGE";
