export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";

export const GET_EDIT_USER_REQUEST = "GET_EDIT_USER_REQUEST";
export const GET_EDIT_USER_SUCCESS = "GET_EDIT_USER_SUCCESS";
export const GET_EDIT_USER_ERROR = "GET_EDIT_USER_ERROR";
