export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const UPDATE_USER_OBJ = "UPDATE_USER_OBJ";
export const REGISTER_USER_INIT = "REGISTER_USER_INIT";
