export const VERIFY_BILL_DATA_REQUEST = "VERIFY_BILL_DATA_REQUEST";
export const VERIFY_BILL_DATA_SUCCESS = "VERIFY_BILL_DATA_SUCCESS";
export const VERIFY_BILL_DATA_ERROR = "VERIFY_BILL_DATA_ERROR";
export const UPDATE_CONSUMED_BILL_DATA_REQUEST = "UPDATE_CONSUMED_BILL_DATA_REQUEST";
export const UPDATE_CONSUMED_BILL_DATA_SUCCESS = "UPDATE_CONSUMED_BILL_DATA_SUCCESS";
export const UPDATE_CONSUMED_BILL_DATA_ERROR = "UPDATE_CONSUMED_BILL_DATA_ERROR";
export const UPDATE_FIELD = "UPDATE_FIELD";
