export const SAVE_MONTHLY_BILL_REQUEST = "SAVE_MONTHLY_BILL_REQUEST";
export const SAVE_MONTHLY_BILL_SUCCESS = "SAVE_MONTHLY_BILL_SUCCESS";
export const SAVE_MONTHLY_BILL_ERROR = "SAVE_MONTHLY_BILL_ERROR";
