export const FORGOT_PASSWORD_USER_REQUEST = "FORGOT_PASSWORD_USER_REQUEST";
export const FORGOT_PASSWORD_USER_SUCCESS = "FORGOT_PASSWORD_USER_SUCCESS";
export const FORGOT_PASSWORD_USER_ERROR = "FORGOT_PASSWORD_USER_ERROR";

export const USER_EXIST_REQUEST = "USER_EXIST_REQUEST";
export const USER_EXIST_SUCCESS = "USER_EXIST_SUCCESS";
export const USER_EXIST_ERROR = "USER_EXIST_ERROR";
