export const GET_CURRENT_BILL_DATA_REQUEST = "GET_CURRENT_BILL_DATA_REQUEST";
export const GET_CURRENT_BILL_DATA_SUCCESS = "GET_CURRENT_BILL_DATA_SUCCESS";
export const GET_CURRENT_BILL_DATA_ERROR = "GET_CURRENT_BILL_DATA_ERROR";

export const SET_CONSUMED_UNITS_REQUEST = "SET_CONSUMED_UNITS_REQUEST";
export const SET_CONSUMED_UNITS_SUCCESS = "SET_CONSUMED_UNITS_SUCCESS";
export const SET_CONSUMED_UNITS_ERROR = "SET_CONSUMED_UNITS_ERROR";
export const SAVE_READING_REQUEST = "SAVE_READING_REQUEST";
export const SAVE_READING_SUCCESS = "SAVE_READING_SUCCESS";
export const SAVE_READING_ERROR = "SAVE_READING_ERROR";

export const R_UPDATE_FIELD = "R_UPDATE_FIELD";
